Repository Fasoo-LLM-Chat-UI-UX/llmchat-frontend, pull requests merged in 2024-06, with the labels that each got.

#8 feat: Create Login, Signup components
  src/assets/check_gray.png
  src/assets/check_white.png
  src/assets/desc_icon1.png
  src/assets/desc_icon2.png
  src/assets/desc_img1.png
  src/assets/desc_img2.png
  src/assets/devicon_google.png
  src/assets/devicon_kakao.png
  src/assets/devicon_naver.png
  src/assets/fasoo_icon.png
  src/assets/lock_icon.png
  src/assets/login_fail_icon.png
  src/components/Login/GoogleRedirect.tsx
  src/components/Login/KakaoRedirect.tsx
  src/components/Login/Login.module.css
  src/components/Login/Login.tsx
  src/components/Login/NaverRedirect.tsx
  src/components/Signup/Signup.module.css
  src/components/Signup/Signup.tsx
Labels: 기능구현, 민균

#13 feat: Create Settings component
  src/assets/settings_basic.png
  src/assets/settings_icon.png
  src/assets/settings_personal.png
  src/assets/settings_select.png
  src/assets/settings_sound.png
  src/assets/settings_version.png
  src/components/Settings/Settings.module.css
  src/components/Settings/Settings.tsx
Labels: 기능구현, 민균

#14 feat: Edit Main chatting page
  .env
  package-lock.json
  package.json
  src/apis/thread.ts
  src/assets/Fasoo.svg
  src/assets/FasooLogo.svg
  src/assets/aerochatLogo.svg
  src/assets/answer.svg
  src/assets/bad.svg
  src/assets/bookmark.svg
  src/assets/clickBad.svg
  src/assets/clickBookmark.svg
  src/assets/clickGood.svg
  src/assets/copy.svg
  src/assets/good.svg
  src/assets/reanswer.svg
  src/assets/send.svg
  src/assets/share.svg
  src/assets/speaker.svg
  src/assets/voice.svg
  src/components/Chat/ChatComponent.css
  src/components/Chat/ChatComponent.tsx
  src/components/MainPage/Chatting/Chatting.module.css
  src/components/MainPage/Chatting/ChattingAnswer.tsx
  src/components/MainPage/Chatting/ChattingQuestion.tsx
  src/components/MainPage/Chatting/QuestionBox.tsx
  src/components/MainPage/iconGroup/iconGroupLeft.tsx
  src/components/MainPage/iconGroup/iconGroupRight.tsx
  src/components/Sidebar/SidebarMenu/SidebarMenu.module.css
  src/components/Sidebar/SidebarMenu/SidebarMenu.tsx
  src/pages/Main.tsx
  src/styles/global.css
Labels: 기능구현, 수빈

#16 feat: Implement responsive design
  src/components/Login/Login.module.css
  src/components/Login/Login.tsx
  src/components/Settings/Settings.module.css
  src/components/Settings/Settings.tsx
  src/components/Signup/Signup.module.css
  src/components/Signup/Signup.tsx
  src/pages/LoginPage/LoginPage.tsx
  src/pages/SignupPage/SignupPage.tsx
Labels: 기능구현, 버그, 민균

#17 feat: Add search page component
  package-lock.json
  package.json
  src/assets/speakStop.svg
  src/components/MainPage/Chatting/Chatting.module.css
  src/components/MainPage/Chatting/QuestionBox.tsx
  src/components/MainPage/iconGroup/iconGroupLeft.tsx
  src/components/SearchResult/SearchResult.module.css
  src/components/SearchResult/SearchResult.tsx
  src/react-app-env.d.ts
  tsconfig.json
Labels: question, 기능구현, 수빈

#19 feat: Implement updated Search api
  src/apis/thread.ts
  src/components/Chat/Chat/Chat.module.css
  src/components/Chat/Chat/Chat.tsx
  src/components/SearchResult/SearchResult.tsx
  src/components/Sidebar/SearchBar/SearchBar.tsx
  src/context/ThreadContext.tsx
  src/index.tsx
  src/types/thread.d.ts
  src/utils/index.ts
  src/utils/search.tsx
Labels: 기능구현, 버그, 현진

#20 feat: Implement responsive design and close modal
  src/components/Settings/Settings.module.css
  src/components/Settings/Settings.tsx
Labels: 기능구현, 민균

#21 feat: Edit main chat page design .etc
  package-lock.json
  package.json
  src/components/MainPage/Chatting/Chatting.module.css
  src/components/MainPage/Chatting/ChattingAnswer.tsx
  src/components/MainPage/Chatting/ChattingQuestion.tsx
  src/components/MainPage/Chatting/QuestionBox.tsx
  src/components/MainPage/iconGroup/iconGroupLeft.tsx
  src/components/SearchResult/SearchResult.module.css
Labels: 기능구현, 수빈

#23 feat: Resolve source map error and Modify select in SearchResult component
  .env
  package-lock.json
  src/apis/thread.ts
  src/components/SearchResult/SearchResult.tsx
  src/components/Sidebar/SearchBar/SearchBar.tsx
  src/components/Sidebar/SidebarMenu/SidebarMenu.tsx
  src/components/Sidebar/SortOptions/SortOptions.tsx
  src/components/Sidebar/index.ts
  src/context/ThreadContext.tsx
Labels: 리팩토링, 버그, 환경구성, 현진

#26 config: Configure develop and production url as .env
  .env.development
  .env.production
  src/components/Chat/ShareModal/ShareModal.tsx
  src/components/Login/Login.tsx
Labels: 환경구성, 현진

#29 fix: Clear previous user data on new login
  src/components/Settings/Settings.tsx
  src/components/Sidebar/ButtonList/ButtonList.tsx
  src/context/ThreadContext.tsx
  src/utils/storage.ts
Labels: 버그, 현진

#30 feat: Modify Share page markdown
  src/pages/SharePage/SharePage.module.css
  src/pages/SharePage/SharePage.tsx
Labels: 기능구현, 현진

#32 fix: Edit share page components layout
  src/pages/SharePage/SharePage.module.css
  src/pages/SharePage/SharePage.tsx
Labels: enhancement, 리팩토링, 수빈

#33 feat: speechSynthesis error
  src/App.tsx
  src/index.tsx
Labels: 리팩토링, 수빈
